### ISSUE TITLE
Long-term PyTrx to-do list

### ISSUE THREAD

**Issue by PennyHow** [PennyHow/PyTrx#35]
- [ ] Better manual delineation functionality in the Area and Line objects (e.g. eliminate the risk of infinite looping)
- [ ] Faster georectification processing. This can either be done by sourcing more efficient methods, or potentially using parrallel processing
- [ ] Faster handling of DEM, so that users that input DEMs with higher spatial resolution and coverage

**Comment by PennyHow** [comment]
- [ ] Move away from gdal as a dependency
